POST http://localhost:8000/generate-video
Content-Type: application/json

{
  "prompt": "A scifi robot playing game"
}

### GENERATE IMAGE ENDPOINT
curl -X POST "http://localhost:8000/generate-image" \
-H "Content-Type: application/json" \
-d '{"prompt": "A futuristic microsoft arc mouse"}'
